### ISSUE TITLE
Missing repo license

### ISSUE THREAD

**Issue by kimpers** [SocialGouv/matomo-next#101]
Hi!

I'm looking to rely on and contribute to this project but the lack of a proper license makes this hard. Could you add license so that we know how we can use the code?

**Comment by revolunet** [comment]
Thanks for reporting and welcome :)

The Apache-2.0 license has been added in https://github.com/SocialGouv/matomo-next/pull/102

**Comment by kimpers** [comment]
Thank you 

> Thanks for reporting and welcome :)
> 
> The Apache-2.0 license has been added in #102

Thank you for quick resolution 🙏
