### ISSUE TITLE
Console logging what's being excluded in tracking

### ISSUE THREAD

**Issue by alizadeh-m** [SocialGouv/matomo-next#121]
Hi,
Unsure if this is an feature, but what I want to know is what the reason is for console logging what is being excluded and can you guys add an prop to opt out of it.

I think this is where in the code this is triggered.
https://github.com/SocialGouv/matomo-next/blob/f10602b1383cc18a3097c68e5192556405d68d7d/src/index.ts#L106C7-L106C72

And this is what I want to opt out of:
![Screenshot 2024-02-13 at 11 40 28](https://github.com/SocialGouv/matomo-next/assets/36159623/57a6f52d-a2fc-4546-a4a4-e19759092ec1)

**Comment by revolunet** [comment]
Hi @alizadeh-m . Could you make a pull request with an optional debug mode (default false) that activate logging if enabled ?
