### ISSUE TITLE
The method enableLinkTracking is registered more than once

### ISSUE THREAD

**Issue by followbl** [SocialGouv/matomo-next#23]
```
instrument.js:110 The method enableLinkTracking is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation
```

Thanks for matomo-next we're utilizing in production. 

Can obviously see this warning thrown in the console is due to two instances of `push(["enableLinkTracking"]);` [here](https://github.com/SocialGouv/matomo-next/blob/master/src/index.js#L75) and above - should this error be a no-op? 

Reading matomo's error explanation article - we're not looking to record the 2nd log (it's the same in our case here)

**Comment by revolunet** [comment]
Hi, thanks for reporting. i guess we can remove the second call `enableLinkTracking` you pointed out. what do you think ?

**Comment by revolunet** [comment]
checkout this PR : https://github.com/SocialGouv/matomo-next/pull/26
