### ISSUE TITLE
workbox caching

### ISSUE THREAD

**Issue by z0lo13** [SocialGouv/matomo-next#34]
When using a workbox for PWA production, a full request is added to the app cache which creates extensive memory usage.

https://mw-pwa-58440ydcn.vercel.app/ (Version with Matomo-next)
Go to dev tools Application Clear Storage and hit update a few times. The cache will be increasing with every hit, my application reached 1gb in the cache usage while the full app size is 50 MB

https://mw-pwa-4vle6e6j6.vercel.app/ (Version without Matomo-next)
Go to dev tools Application Clear Storage and hit update a few times. As soon as the app fully cached (26 MB or so), it will not increase with reloading

![image](https://user-images.githubusercontent.com/23143958/96648363-3b8c2c00-12fd-11eb-832d-1ca7cc78a1c5.png)

**Comment by revolunet** [comment]
Hi, its true the first URL has more data in cache but without the code its hard to tell. it doesnt go over 74mb in my case

Looks like the "cache storage" is huge in your case and if you dig into it you can see its some vercel related stuff

i use this code on non vercel deployments and have nothing stored in "cache storage". 

so i guess its not related; please reopen if i missed something
