### ISSUE TITLE
Which value should I put on NEXT_PUBLIC_MATOMO_URL and NEXT_PUBLIC_MATOMO_SITE_ID env vars?

### ISSUE THREAD

**Issue by victorcarvalhosp** [SocialGouv/matomo-next#65]
Hi team,

I'm trying to setup matomo, but I have no clue which values should I put on these two env vars. Can you please point where I can find it on matomo so I can add it to our env vars properly?

Thanks!

**Comment by revolunet** [comment]
Thanks @rap2hpoutre
