### ISSUE TITLE
Feature: allow disabling of cookie usage

### ISSUE THREAD

**Issue by genox** [SocialGouv/matomo-next#83]
Hi,

It would be nice to set wether cookies are used to track or not at `init()`.

**Comment by sylvainlg** [comment]
Hi,

I think the opt-out behaviour can be a interesting feature too :
https://matomo.org/blog/2022/09/improvements-to-matomo-opt-out-form-feature/

**Comment by vivi90** [comment]
@genox Why not using
```typescript
push(['disableCookies']);
```
right after using `init()`?

**Comment by Christian1984** [comment]
i would like to implement this adding `disableCookies?: boolean` with default `false` to `InitSettings`and then processing it during `init()` would be a simple fix. i would want that. do you accept prs? cheers 🍻

**Comment by revolunet** [comment]
Yes thanks, we accept PRs with tests ;)

**Comment by Christian1984** [comment]
> Yes thanks, we accept PRs with tests ;)

🥳 awesome. you got yourself a PR to review 😅
